app:
  language: english
  level: 0
  problem_grid: resources/problem-grids/L2_P3.json
  results: temp_dir/results.json
levels:
  '0.0':
    file: resources/problem-grids/L0_P0.json
    name: Go home
    space: 
        - Test
        - IPS678
  '0.1':
    file: resources/problem-grids/L0_P1.json
    name: Go home
    space: 
        - PES  
        - IPS
        - Test
        - IPS678
  '0.2':
    file: resources/problem-grids/L0_P2.json
    name: All homes
    space: 
        - PES
        - IPS
        - Test
        - IPS678
  '0.3':
    file: resources/problem-grids/L0_P3.json
    name: Shortest Path
    space: 
        - PES   
        - IPS
        - Test
        - IPS678
  '1.1':
    file: resources/problem-grids/L1_P1.json
    name: Total coins in grid
    space:   
        - IPS
        - IPS678
        - Test
  '1.2':
    file: resources/problem-grids/L1_P2.json
    name: Difference in coins
    space:   
        - IPS
        - Test
        - IPS678
  '1.3': 
    file: resources/problem-grids/L1_P3.json
    name: Divide the total coins by two
    space:   
        - IPS
        - Test
        - IPS678
  '2.1':
    file: resources/problem-grids/L2_P1.json
    name: Total number of coins equals 5
    space:   
        - IPS
        - Test
        - IPS678
  '2.2':
    file: resources/problem-grids/L2_P2.json
    name: Total number of coins greater than or equal to 10
    space:   
        - IPS
        - Test
        - IPS678
  '2.3':
    file: resources/problem-grids/L2_P3.json
    name: Total number of coins lesser than 30
    space:   
        - IPS
        - Test
        - IPS678
  '3.1':
    file: resources/problem-grids/L3_P1.json
    name: Colour boundary
    space:   
        - IPS
        - Test
        - IPS678
  '3.2.0':
    file: resources/problem-grids/L3_P2.json
    name: Colour alternate boxes
    space:   
        - IPS
        - Test
  '3.3':
    file: resources/problem-grids/L3_P3.json
    name: Colour boxes that have coin bags
    space:   
        - IPS
        - Test
  '4.1': 
    file: resources/problem-grids/L4_P1.json
    name: Loop to colour the boundary of the grid
    space:   
        - IPS
        - Test
  '4.2': 
    file: resources/problem-grids/L4_P2.json
    name: Loop through the grid to get home
    space:   
        - IPS
        - Test
  '4.3': 
    file: resources/problem-grids/L4_P3.json
    name: Loop to colour alternate boxes in the row.
    space:   
        - IPS
        - Test
  '3.2': 
    file: resources/problem-grids/L4_P4.json
    name: Loop to count the total number of coins in the grid.
    space:   
        - IPS
        - Test
        - IPS678